# Chinese - English NBA teams Name 

NBATeamCN = {
    "骑士":"Cavaliers",
    "热火":"Heat",
    "步行者":"Pacers",
    "公牛":"Bulls",
    "尼克斯":"Knicks",
    "凯尔特人":"Celtics",
    "活塞":"Pistons",
    "猛龙":"Raptors",
    "篮网":"Nets",
    "奇才":"Wizards",
    "魔术":"Magic",
    "76人":"76ers",
    "山猫":"Bobcats",
    "雄鹿":"Bucks",
    "老鹰":"Hawks",
    "雷霆":"Thunder",
    "勇士":"Warriors",
    "快船":"Clippers",
    "湖人":"Lakes",
    "国王":"Kings",
    "马刺":"Spurs",
    "独行侠":"Mavericks",
    "火箭":"Rockets",
    "掘金":"Nuggets",
    "开拓者":"Trailblazers",
    "太阳":"Suns",
    "灰熊":"Grizzlies",
    "森林狼":"Timberwolves",
    "鹈鹕":"Pelicans",
    "爵士":"Jazz"
}
